<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_radix-_r2un</name>
   <tag></tag>
   <elementGuidId>f9473318-5170-44aa-b39c-ee5c0910bfef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;radix-\:r2m4\:&quot;] [data-cy=&quot;payment-group-&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'radix-:r2m4:']//*[@data-cy = 'payment-group-']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95363d60-fa5b-46b8-ae2f-58d5635c2abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5f060d98-c902-4691-bf56-99a3cceffbfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r2uo:</value>
      <webElementGuid>f6f82a75-da22-48ce-be22-789d13712ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc92c22c-70fa-4852-bb4a-ebd139ec2006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>ea213da8-fa9d-449a-ba72-00823ccc0ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>da1a6918-2746-4896-afa9-a5dde1d2b045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r2un:</value>
      <webElementGuid>dcf49349-0500-4b04-8871-879995ad64a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-1 items-center justify-between py-4 transition-all [&amp;[data-state=open]>svg]:rotate-180 w-full border-b border-border-secondary !py-3 font-semibold text-black hover:no-underline [&amp;>svg]:h-6 [&amp;>svg]:w-6 [&amp;>svg]:text-brand</value>
      <webElementGuid>0440777c-cb70-41a7-832b-3224f59f393c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>payment-group-</value>
      <webElementGuid>db77ae25-6921-437d-a5a7-77bc472c7104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cd573acc164863a5cd81bad9256d440d</value>
      <webElementGuid>4f0192b9-14b4-4a90-bbed-57339cd7825a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'radix-:r2m4:']//*[@data-cy = 'payment-group-']</value>
      <webElementGuid>c7eb99cc-3c69-452b-9754-2e69cca1afbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'radix-:r2m4:']//*[@data-cy = 'payment-group-']</value>
      <webElementGuid>40d7735b-f005-4bea-bfab-b49e2add5109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:r2un:']</value>
      <webElementGuid>99b1d7fc-35fd-4e1f-9a1b-9016ea8f11c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
