<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Email</name>
   <tag></tag>
   <elementGuidId>e6f78aa1-0d29-4495-9a68-3d9ee6a05b44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;identifier&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'identifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23825dde-803c-498e-ae1c-cfe3268b4bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex w-full rounded-md border-border-secondary px-3 py-2 text-sm transition-colors ease-in-out file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-secondary-foreground focus-visible:outline-none focus:border-2 focus:border-primary disabled:cursor-not-allowed disabled:opacity-50 h-12 !h-12 min-w-full border !bg-transparent</value>
      <webElementGuid>3fca28f0-65d9-4069-ad85-b27c976ffa16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r2ud:-form-item</value>
      <webElementGuid>ecb431df-bd31-4379-b70f-f7d3ef92303c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r2ud:-form-item-description</value>
      <webElementGuid>48077b0e-65a0-47f1-bc7e-2b1766e9ab3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db454aaa-e1b5-4add-a59a-6b40ee36d27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>13483c11-84cc-4ec4-83e1-d8b154e47a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>4c242351-0666-4fbb-9007-92debc066a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-47d476cfe27dfab80e12b124e922c827</value>
      <webElementGuid>d95edb82-6ae0-437f-a0ff-53b262ee43d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'identifier']</value>
      <webElementGuid>dd2a6a7d-6384-4ee9-a424-a5837ad6c1e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'identifier']</value>
      <webElementGuid>fccf491f-72cc-4a2b-8b7c-52dc61c573a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = ':r2ud:-form-item' and @name = 'identifier']</value>
      <webElementGuid>25591fe4-1f32-4ef9-b434-d6fa266c1cce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
