<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Input ini wajib diisi</name>
   <tag></tag>
   <elementGuidId>273443ef-ec4b-4f4c-af07-cb26a34027fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r88i:-form-item-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>df631862-36cc-4573-8a2c-66e1c3736491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r88i:-form-item-message</value>
      <webElementGuid>dca854ec-c7a4-4298-bce3-b2d09c104a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-1 font-medium text-destructive text-[8pt]</value>
      <webElementGuid>5c065e6c-98cd-4e08-83f2-28fb178c4218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Input ini wajib diisi</value>
      <webElementGuid>dfa61607-f0b2-4520-b0f2-1d734a5c6605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r88i:-form-item-message&quot;)</value>
      <webElementGuid>6523663b-e115-447a-88d7-3535b2429d16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r88i:-form-item-message']</value>
      <webElementGuid>5b35e44d-fd19-49c3-b540-8ca2f09ba62f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-form']/div[2]/div[2]/div/div/div/p</value>
      <webElementGuid>39c98ce6-999f-4283-a062-02aa661a65c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::p[1]</value>
      <webElementGuid>7d93bc8b-47dc-47d9-9ab1-be6b373791e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Denomination'])[1]/preceding::p[2]</value>
      <webElementGuid>da8e9b80-7b66-4953-b579-f70f798e456c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/p</value>
      <webElementGuid>d9070cc7-a92f-4def-b90e-eb6de8e21bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r88i:-form-item-message' and (text() = 'Input ini wajib diisi' or . = 'Input ini wajib diisi')]</value>
      <webElementGuid>3e91f473-eb30-4140-a8bc-f7369138c78b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
