<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_radix-_r54d</name>
   <tag></tag>
   <elementGuidId>b6f08ee5-5bbb-40a6-9dd3-eb3a3a5eca6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;radix-\:r4sl\:&quot;] [data-cy=&quot;payment-group-&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'radix-:r4sl:']//*[@data-cy = 'payment-group-']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c1003fbb-a989-422d-8cd0-a88ac769bd18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>050ac73d-bdcd-473d-8932-55b17006dbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-:r54e:</value>
      <webElementGuid>c3dc0505-9f5f-43e8-a965-4e632cfd4d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a70c6b2-84fd-4fbf-b246-ea3d8241015a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>7a6e8d18-bce2-4062-89f8-fa53a2f90293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-orientation</name>
      <type>Main</type>
      <value>vertical</value>
      <webElementGuid>8d7d3d49-0231-4fff-b61d-b0897a67a7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-:r54d:</value>
      <webElementGuid>5f20fc64-c5ff-4b72-947d-0589d3407f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex flex-1 items-center justify-between py-4 transition-all [&amp;[data-state=open]>svg]:rotate-180 w-full border-b border-border-secondary !py-3 font-semibold text-black hover:no-underline [&amp;>svg]:h-6 [&amp;>svg]:w-6 [&amp;>svg]:text-brand</value>
      <webElementGuid>2212f630-df6c-4e50-84e7-29032b3288b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>payment-group-</value>
      <webElementGuid>9429c108-ac5f-4709-8e92-c0ab71a74be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0af97cdb0ec5e3c5d78c4b2301a60c52</value>
      <webElementGuid>cb7f1b03-1e52-4896-98ae-6d92268cd93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'radix-:r4sl:']//*[@data-cy = 'payment-group-']</value>
      <webElementGuid>82a3a4b0-5953-4534-9d6d-f4269b160c22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'radix-:r4sl:']//*[@data-cy = 'payment-group-']</value>
      <webElementGuid>8d7a63e8-9d64-4cb4-b849-25d192e5da7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'radix-:r54d:']</value>
      <webElementGuid>94785124-5e38-4d68-9c8f-3a1a0a728d46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
