<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Email</name>
   <tag></tag>
   <elementGuidId>ae68696c-ca69-40f5-823e-92bd0f806fa2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;identifier&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'identifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f70d6835-0722-4a07-a6e2-77b50ab4b722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex w-full rounded-md border-border-secondary px-3 py-2 text-sm transition-colors ease-in-out file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-secondary-foreground focus-visible:outline-none focus:border-2 focus:border-primary disabled:cursor-not-allowed disabled:opacity-50 h-12 !h-12 min-w-full border !bg-transparent</value>
      <webElementGuid>fb07922d-1529-49a9-84fc-65f61d6c6aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r4sj:-form-item</value>
      <webElementGuid>4beaf97f-0502-4d26-8137-b2a6b523a2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r4sj:-form-item-description</value>
      <webElementGuid>a47c9d41-3707-4f59-8db6-764aa34efff9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a338d31b-2457-447b-9def-ec02485fa2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>67a6281e-6607-4416-aced-d34029cada81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>02353149-e34b-442f-b83f-3a6a5b1a57e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-47d476cfe27dfab80e12b124e922c827</value>
      <webElementGuid>a57f9175-62a9-4e5b-9ef4-9580e664736f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'identifier']</value>
      <webElementGuid>0342e152-db26-4874-9561-d447b4f35a86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'identifier']</value>
      <webElementGuid>9dd285dd-dc8c-43d2-927c-ce1f8d1ff9e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = ':r4sj:-form-item' and @name = 'identifier']</value>
      <webElementGuid>1275380d-4e03-4b62-a530-203379632afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
