<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Phone Number tidak ditemukan. Harap guna_a3bed4</name>
   <tag></tag>
   <elementGuidId>a91aa303-6207-457e-b934-ddabe7eac0ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>dc9e062d-0845-4296-8721-96d949002a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>d9b67294-6c7d-4b55-86d2-b18ccf0b9ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-atomic</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b18ecf3e-12f5-4558-bb3b-29c6fd413fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>3faa256a-307e-4443-8573-8459c0a99c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a087d185-b7d9-4b32-95b0-0370846abff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground border-0 group-[.toaster]:shadow-lg !bg-[#fadfe5] !text-[#e02a54]</value>
      <webElementGuid>fed2abe5-34c4-4597-8722-c9cd3338232a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-styled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8948aa99-7af9-4b85-ad46-09adbd546d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mounted</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>12484de1-e514-4aed-a8a0-83d48ca57257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-promise</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc774b63-28e8-4939-8478-9a5c3b1b6b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-removed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e3652b4-8b63-4681-b7be-f845f020cb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-visible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a3a0b288-a45b-48fb-95c9-6c7d2774a177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-y-position</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>76ab7547-a08e-4d68-abd9-736b2b34f172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-x-position</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>2985a3ed-36d1-4921-8529-c47ecc7cb83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>adcc1e30-940f-4fc6-a3e4-b5801c839c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-front</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffb035df-bc72-49a5-ab14-b96c9931ba09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swiping</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a0d2fbea-1147-4ef9-90af-e75f4c8f21f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismissible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f1414094-164d-4305-a45a-1a6964e7c68a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>f0c3278c-767e-4a4a-ac62-8c6db0ce936f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-swipe-out</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b1197cf0-b808-4d66-ab0c-756b71659fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6ef892ac-45f4-407b-8b79-71b38cf7e439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone Number tidak ditemukan. Harap gunakan data yang valid dan terdaftar</value>
      <webElementGuid>d608324f-b36b-4ef9-a800-9aab6e282fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__className_646807&quot;]/section[1]/ol[@class=&quot;toaster group&quot;]/li[@class=&quot;group toast group-[.toaster]:bg-background group-[.toaster]:text-foreground border-0 group-[.toaster]:shadow-lg !bg-[#fadfe5] !text-[#e02a54]&quot;]</value>
      <webElementGuid>58b7a1dd-a0e2-4482-902c-111e7603dc8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::li[1]</value>
      <webElementGuid>ca69d866-e8b3-456b-b237-f0e2d9121936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>58917856-6e14-43ca-ad82-497267d725eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Phone Number tidak ditemukan. Harap gunakan data yang valid dan terdaftar' or . = 'Phone Number tidak ditemukan. Harap gunakan data yang valid dan terdaftar')]</value>
      <webElementGuid>e6c0820f-e418-4bc5-a7be-7fb0e0045a33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
