<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Konfirmasi Password Baru</name>
   <tag></tag>
   <elementGuidId>d1080452-fb72-4c9f-9322-c3ab0d9ddf54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;confirmPassword&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'confirmPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d6d20a3-9472-4953-962c-2da3a128c53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>202db467-d953-442d-8523-458b37e4a20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>relative flex w-full rounded-md border-border-secondary px-3 py-2 text-sm transition-colors ease-in-out file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-secondary-foreground focus-visible:outline-none focus:border-2 focus:border-primary disabled:cursor-not-allowed disabled:opacity-50 !h-12 border !bg-transparent hide-password-toggle pr-10 mb-4 h-11 min-w-full</value>
      <webElementGuid>c3e4cfb5-9f78-46ed-9513-29322e18ed3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r5:-form-item</value>
      <webElementGuid>0619d4ed-ca44-4a12-985a-ed6acbb759e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>:r5:-form-item-description</value>
      <webElementGuid>2082de86-3591-41d2-a242-ff60c674f9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e1b211d3-83c6-4933-843f-1ae121b7eaef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>e72ea6d5-658a-4cc7-afc1-0c8240d5f8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirmPassword</value>
      <webElementGuid>5cd8a926-7948-4d71-97e4-1a8776d29379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c14d555f9c1f60256b17f6c1e7da48bd</value>
      <webElementGuid>67b8e30a-32d7-4ac8-834f-c50320764fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'confirmPassword']</value>
      <webElementGuid>a373d200-2073-41f4-9304-fa301a257a45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'confirmPassword']</value>
      <webElementGuid>44ada468-20bb-4bac-8053-6ae0de888c9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = ':r5:-form-item' and @type = 'password' and @name = 'confirmPassword']</value>
      <webElementGuid>a483f24a-7009-498a-a9ec-ef5f0a4eeeea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
