<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Alamat email sementara yang aman dan anonim_copyBtn</name>
   <tag></tag>
   <elementGuidId>7b09a863-5556-4b11-9c2e-88719827ce31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#copyBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='copyBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ac677522-962c-43f4-b1e0-c4cbe3428ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>copy-btn</value>
      <webElementGuid>75390108-5011-4208-abe1-312739cbdaa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>copyBtn</value>
      <webElementGuid>362f5a61-cced-4f11-ae1b-fdca2f31aab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-translate-title</name>
      <type>Main</type>
      <value>copy-title</value>
      <webElementGuid>e0080e69-5ff9-4ecd-80dc-1fb6653c20f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;copyBtn&quot;)</value>
      <webElementGuid>f616d688-4584-4dc1-8cb3-456edaf3d590</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='copyBtn']</value>
      <webElementGuid>aef3fc90-0531-4dc7-bf3e-8176a5b1b714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat email sementara yang aman dan anonim'])[1]/following::button[1]</value>
      <webElementGuid>b2ff81e4-d294-4b6e-9457-f6c4445437d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa Indonesia'])[1]/following::button[1]</value>
      <webElementGuid>77e78126-0da6-42ba-8125-c5d2cf9fe6b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ganti alamat'])[1]/preceding::button[2]</value>
      <webElementGuid>25dbed6c-b603-4453-b89a-94b6a5ae9c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kotak masuk'])[1]/preceding::button[3]</value>
      <webElementGuid>cae6ff41-f1a0-4cdd-9140-d82c46b9482e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/button</value>
      <webElementGuid>6300705d-a371-423e-b5b6-3565f4cc1e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'copyBtn']</value>
      <webElementGuid>46822336-c3d6-4be1-a785-d599cacd9774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
