<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Your OTP Code_closeModal</name>
   <tag></tag>
   <elementGuidId>c5727c97-1c76-4227-8b90-1140bcad88ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeModal</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='closeModal']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a6d8fa03-435f-407c-8860-0d7de40b022d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close-btn</value>
      <webElementGuid>e771a5f1-9847-4ad0-b0af-536d175afab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeModal</value>
      <webElementGuid>01ec7687-d3b6-4d18-89e9-536ed5c4ec78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeModal&quot;)</value>
      <webElementGuid>c631bd6d-3244-4da3-8347-7c9350912711</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='closeModal']</value>
      <webElementGuid>8dbb5393-7e40-4076-aebb-c4f229c0680f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='emailModal']/div/div/button</value>
      <webElementGuid>2c537a0b-9aa1-49a3-b199-b514130a937a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your OTP Code!'])[2]/following::button[1]</value>
      <webElementGuid>88d2c8b6-37bb-45b1-8696-795ab3954c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apakah bisa digunakan perusahaan?'])[1]/following::button[1]</value>
      <webElementGuid>b1a110dd-4320-4221-b69d-53906996e794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengirim:'])[1]/preceding::button[1]</value>
      <webElementGuid>18fc293a-712c-4d19-a9b8-ccd9622ec2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='no_reply@vocagame.com'])[2]/preceding::button[1]</value>
      <webElementGuid>7a584b69-4e7f-4484-9ff9-bfc955482543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>a7c0a3f6-4196-472a-ba81-69db1340ddb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'closeModal']</value>
      <webElementGuid>18ec976e-8ffd-44ed-9fcb-91ac1bc0ac7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
