<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_OTP</name>
   <tag></tag>
   <elementGuidId>d754056f-dec7-4cc7-b545-49e95e1686bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61fe8cfd-c130-4559-95ad-ac5ba94a3f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>one-time-code</value>
      <webElementGuid>eb0667dc-90bd-40df-9991-efddf363e077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled:cursor-not-allowed</value>
      <webElementGuid>16b837dc-1131-4c51-ba54-3e753df52554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4f428232-6e5b-464c-8a18-7c449274fa65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp-placeholder-shown</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb3c87f6-fdc5-40e8-b584-5090d24936fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>c59d33a2-37ec-4100-845a-3c77d606c6d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^\d+$</value>
      <webElementGuid>300bbd8b-a26a-4f12-98cf-4c3ae7f6a2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>2c882910-1405-4376-942b-1d4f62bcaf2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp-mss</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e2a9e6d1-5500-4aeb-aceb-0f91f5f9fd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-input-otp-mse</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24cad234-890e-4ecd-8522-06c2fc6cd510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-:R2efnj2f9ejsq:&quot;)/div[@class=&quot;px-5 sm:px-0&quot;]/form[@class=&quot;mt-4 space-y-4&quot;]/div[@class=&quot;flex items-center justify-between p-1 my-8 overflow-hidden&quot;]/div[@class=&quot;flex items-center w-full justify-between gap-2 has-[:disabled]:opacity-50&quot;]/div[7]/input[@class=&quot;disabled:cursor-not-allowed&quot;]</value>
      <webElementGuid>838df339-ba0d-4714-ba86-766928dadde1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>adf62f7c-1634-4a8a-b973-aa1274c0bb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-:R2efnj2f9ejsq:']/div/form/div/div/div[7]/input</value>
      <webElementGuid>aa14f091-c524-49d9-a6f8-e9e6bc36a31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[7]/input</value>
      <webElementGuid>66b32a28-0b71-4526-b44f-c2ffdcb639d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
