<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OTP</name>
   <tag></tag>
   <elementGuidId>b0ec80c0-9fde-4b7c-b4a2-c6e85a21e4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inbox']/div[2]/div/div/div[3]/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>88ec81b0-9e08-445f-91ab-03b046f10181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>008801</value>
      <webElementGuid>315ee2ba-6b25-4f97-b1f3-da9642a350a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inbox&quot;)/div[@class=&quot;flex overflow-y-scroll&quot;]/div[@class=&quot;flex h-full w-screen&quot;]/div[@class=&quot;flex w-full flex-col space-y-5 overflow-y-scroll p-10&quot;]/div[@class=&quot;flex w-full flex-col&quot;]/div[1]/div[1]/p[1]</value>
      <webElementGuid>8eb71423-9593-4a55-92c2-ca5ada71e8ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='inbox']/div[2]/div/div/div[3]/div/div/p</value>
      <webElementGuid>2b74c376-e948-489e-a3c1-326b385475a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Temporary Email'])[1]/following::p[14]</value>
      <webElementGuid>661dfff8-ae7e-4465-94a4-4132007f5646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[2]/following::p[14]</value>
      <webElementGuid>56e50a16-96ac-4080-abc4-e6d0d172fdb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='with Internxt'])[1]/preceding::p[8]</value>
      <webElementGuid>1f6a4d0f-edb0-4302-bb6c-1cf9b3e25739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get 1 GB'])[1]/preceding::p[9]</value>
      <webElementGuid>03437935-5600-49e6-9ab9-9ca126ca404f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='008801']/parent::*</value>
      <webElementGuid>5042e9eb-9ad2-4ec8-8ee6-40b43168ce83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/p</value>
      <webElementGuid>a42a60b2-9801-4b92-b0f9-4362ecad9bb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '008801' or . = '008801')]</value>
      <webElementGuid>a9f61409-18fd-4187-b739-4a1774db9d16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
