<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_990453</name>
   <tag></tag>
   <elementGuidId>84ae5894-283e-424c-a35e-e66e9235df9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div > div > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]/body[1]/div[1]/div[1]/p[1]'])[1]/preceding::p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2355fdac-3b4f-4088-bb36-f92ce1ba37b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>990453</value>
      <webElementGuid>7d79a3f2-4cff-4621-ba58-b29fcc1ce65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[1]/div[1]/p[1]</value>
      <webElementGuid>5e8041f6-93f2-49a5-ae13-9d2c48270c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Register/iframe_Waktu_h-105 w-full border-none</value>
      <webElementGuid>fe736094-4b9d-4b9f-b58b-b8a547799372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/html[1]/body[1]/div[1]/div[1]/p[1]'])[1]/preceding::p[2]</value>
      <webElementGuid>bbd60d4f-8228-471b-95a6-36c886db98cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='990453']/parent::*</value>
      <webElementGuid>07258126-6c23-445f-96c9-7163faea8346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p</value>
      <webElementGuid>05f1845c-9803-4991-b98b-18d369aea27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = '990453' or . = '990453')]</value>
      <webElementGuid>c7546804-75d3-4d68-b408-fdd741c53edc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
