<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Harap masukkan alamat email yang valid</name>
   <tag></tag>
   <elementGuidId>36743fb4-24c6-4cf8-8728-b9a65874462a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r3:-form-item-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5ef1d449-6e66-47d5-a7a6-3e004693c5e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r3:-form-item-message</value>
      <webElementGuid>b3c2c952-d0ca-42ef-bfaf-77b83672b08b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-1 font-medium text-destructive h-0 text-[8pt]</value>
      <webElementGuid>8f45d6c6-fdbb-41e3-a448-482f58aafc43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Harap masukkan alamat email yang valid.</value>
      <webElementGuid>c2dd6e88-8888-49b7-b1e7-a6ae89459498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r3:-form-item-message&quot;)</value>
      <webElementGuid>70744716-dd98-4fbb-947b-78e356db1c53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r3:-form-item-message']</value>
      <webElementGuid>9f9a7c95-542b-41cf-a6ba-96ddf214cb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::p[1]</value>
      <webElementGuid>bdd5a3ea-9fd4-4f2a-92b2-090109afe243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show password'])[1]/preceding::p[1]</value>
      <webElementGuid>38ef5043-a424-4ef4-9da0-d43d2f9e624e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Harap masukkan alamat email yang valid.']/parent::*</value>
      <webElementGuid>faa3b860-cb0a-441c-8e48-f11063f24617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/p</value>
      <webElementGuid>cbba8379-b002-4191-961f-09cd1c0581e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r3:-form-item-message' and (text() = 'Harap masukkan alamat email yang valid.' or . = 'Harap masukkan alamat email yang valid.')]</value>
      <webElementGuid>ca7b59a2-d94e-4ba7-b813-2690933f88af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
