<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Nama belakang harus terdiri dari setidaknya 2 karakter</name>
   <tag></tag>
   <elementGuidId>e190fa9e-f157-46a7-b1a6-f818cfd8e7b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id=':r1:-form-item-message']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7ed507c6-2a41-43c4-9622-8714d12b4e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>:r1:-form-item-message</value>
      <webElementGuid>ccd3b987-5cea-416c-9855-555e192ecc0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pb-1 font-medium text-destructive h-0 text-[8pt]</value>
      <webElementGuid>8e14c728-b386-4e6f-a792-e761bf0670a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nama belakang harus terdiri dari setidaknya 2 karakter.</value>
      <webElementGuid>26226021-5141-40a1-9505-ffb9f3ee51eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r1:-form-item-message&quot;)</value>
      <webElementGuid>4fe0ca86-7ea2-4f8f-acaa-8a8d8d618b95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id=':r1:-form-item-message']</value>
      <webElementGuid>18fbd6e2-9802-4c15-ae6a-49a565ec9d33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::p[1]</value>
      <webElementGuid>d38288a6-0903-4346-a890-53c56010c4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afghanistan'])[1]/preceding::p[1]</value>
      <webElementGuid>5f63e4cf-bab7-460b-ba6c-74235b37cd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Albania'])[1]/preceding::p[1]</value>
      <webElementGuid>8da15417-c383-4a8b-99f3-e73811df4bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nama belakang harus terdiri dari setidaknya 2 karakter.']/parent::*</value>
      <webElementGuid>335e3697-811b-48f9-bfe0-e2f1fa2ca313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p</value>
      <webElementGuid>ca9c1ad0-97cd-43f1-b3f1-f688608ecbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = ':r1:-form-item-message' and (text() = 'Nama belakang harus terdiri dari setidaknya 2 karakter.' or . = 'Nama belakang harus terdiri dari setidaknya 2 karakter.')]</value>
      <webElementGuid>35afc60d-2d9a-4510-afd4-0300d731017a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
